---
- name: Configure Cisco cluster hardware
  hosts: rhv_hosts
  gather_facts: no
  max_fail_percentage: 0
  vars_files:
  - vars/hardware.yml
  tags: ['never', 'hw', 'bios', 'cisco']
  roles:
  - hw_cisco_bios
