---
- name: Update RHV Manager
  hosts: rhv_hosts, rhvm
  gather_facts: no
  max_fail_percentage: 0
  tags: ['never', 'rhv', 'manager']
  roles:
  - rhv_manager_update

### XXX TODO XXX HOST UPDATES ###
