---
- name: Update RHV Manager
  hosts: rhv_hosts, rhvm
  gather_facts: no
  max_fail_percentage: 0
  tags: ['never', 'rhv', 'manager']
  roles:
  - rhv_manager_update

- name: Update RHV Hosts
  hosts: rhv_hosts
  gather_facts: no
  max_fail_percentage: 0
  tags: ['never', 'rhv', 'hosts']
  serial: 1
  roles:
  - ovirt_auth_token_obtain
  - rhv_host_update
  - ovirt_auth_token_revoke
