---
- name: Move RHV Manager out of Global Maintenance mode
  shell: hosted-engine --set-maintenance --mode=none
  when: inventory_hostname in groups.rhv_hosts
  run_once: true

- name: Wait for Maintenance mode change to propagate
  shell: hosted-engine --vm-status | grep state= | grep -v state=Engine || true
  register: he_status
  changed_when: false
  until: he_status.stdout|length == 0
  retries: 20
  delay: 10
  when: inventory_hostname in groups.rhv_hosts
