---
### XXX TODO FIXME FOR RHV 4.4 ###
- name: Abort if local backup directory is not defined
  fail:
    msg: Local backup directory rhvm_local_backup_dir not defined
  when: rhvm_local_backup_dir is not defined
  delegate_to: localhost
  run_once: true

- name: Set timestamp for created files
  set_fact:
    rhvm_backup_tstamp: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M-%S') }}"

- name: Set backup file name
  set_fact:
    rhvm_backup_file: "{{ cluster_name }}_rhvm_backup_{{ rhvm_backup_tstamp }}.tar.xz"
  when: rhvm_backup_file is not defined

- name: Set backup log file name
  set_fact:
    rhvm_backup_log_file: "{{ cluster_name }}_rhvm_backup_{{ rhvm_backup_tstamp }}.log"
  when: rhvm_backup_log_file is not defined

- name: Verify RHV Manager status
  shell: hosted-engine --vm-status | grep status
  register: he_status
  failed_when: '"good" not in he_status.stdout'
  changed_when: false
  when: inventory_hostname in groups.rhv_hosts

- name: Create local backup directory
  file:
    path: "{{ rhvm_local_backup_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Activate RHV Manager Global Maintenance mode
  include_role:
    name: rhv_manager_maintenance_on

- name: Stop httpd
  service:
    name: httpd
    state: stopped
  when: inventory_hostname in groups.rhvm

- name: Stop ovirt-fence-kdump-listener
  service:
    name: ovirt-fence-kdump-listener
    state: stopped
  when: inventory_hostname in groups.rhvm

- name: Stop ovirt-engine-dwhd
  service:
    name: ovirt-engine-dwhd
    state: stopped
  when: inventory_hostname in groups.rhvm

- name: Stop ovirt-engine
  service:
    name: ovirt-engine
    state: stopped
  when: inventory_hostname in groups.rhvm

- name: Run engine-backup in backup mode
  shell: >
    engine-backup
    --mode=backup
    --scope=all
    --file=/var/tmp/{{ rhvm_backup_file }}
    --log=/var/tmp/{{ rhvm_backup_log_file }}
    --tmpdir=/var/tmp
    --archive-compressor=xz
    --files-compressor=xz
    --db-compressor=xz
    --dwh-db-compressor=xz
    --reports-db-compressor=xz
    --db-dump-format=custom
    --dwh-db-dump-format=custom
    --reports-db-dump-format=custom
  register: eb_status
  failed_when: false
  when: inventory_hostname in groups.rhvm

- name: Start ovirt-engine
  service:
    name: ovirt-engine
    state: started
  when: inventory_hostname in groups.rhvm

- name: Start ovirt-engine-dwhd
  service:
    name: ovirt-engine-dwhd
    state: started
  when: inventory_hostname in groups.rhvm

- name: Start ovirt-fence-kdump-listener
  service:
    name: ovirt-fence-kdump-listener
    state: started
  when: inventory_hostname in groups.rhvm

- name: Start httpd
  service:
    name: httpd
    state: started
  when: inventory_hostname in groups.rhvm

- name: Download RHV Manager backup file to local backup directory
  fetch:
    src: "/var/tmp/{{ rhvm_backup_file }}"
    dest: "{{ rhvm_local_backup_dir }}/{{ rhvm_backup_file }}"
    flat: yes
  when: inventory_hostname in groups.rhvm and eb_status.rc == 0

- name: Download log file if backup failed
  fetch:
    src: "/var/tmp/{{ rhvm_backup_log_file }}"
    dest: "{{ rhvm_local_backup_dir}}/{{ rhvm_backup_log_file }}"
    flat: yes
  when: inventory_hostname in groups.rhvm and eb_status.rc != 0

- name: Remove backup file from RHV Manager
  file:
    path: "/var/tmp/{{ rhvm_backup_file }}"
    state: absent
  when: inventory_hostname in groups.rhvm

- name: Remove backup log file from RHV Manager
  file:
    path: "/var/tmp/{{ rhvm_backup_log_file }}"
    state: absent
  when: inventory_hostname in groups.rhvm

- name: Deactivate RHV Manager Global Maintenance mode
  include_role:
    name: rhv_manager_maintenance_off

- name: Terminate with failure if backup failed
  fail:
    msg: Backup failed! Please investigate {{ rhvm_local_backup_dir}}/{{ rhvm_backup_log_file }}.
  when: inventory_hostname in groups.rhvm and eb_status.rc != 0
